### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by Quoteme** [maemo-leste-extras/mihphoto#1]
I see no makefile or anything. Could you please tell me how I would go about compiling this software?

**Comment by parazyd** [comment]
You need to use qt's `qmake` with the mihphoto.pro file.

**Comment by parazyd** [comment]
@Quoteme Have you managed?

**Comment by Quoteme** [comment]
Hi, yeah it worked! Everything turned out fine. Thank you a lot.
I have also wirtten a [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) which would allow arch-linux users to install this software in just one command. The PKGBUILD can be found here:

https://gist.github.com/Quoteme/a216dbd7de158f57ec6e32ee1faa5aad

If you like I can also upload it to the AUR, or would you like to do that?

**Comment by parazyd** [comment]
Sure, feel free to upload it! I don't maintain packages in the AUR since quite a while.

I will close this ticket then :) Cheers!
